name: Build PDFs
on:
  push:
    branches:
      - main

jobs:
  build-pdfs:
    runs-on: ubuntu-latest
    steps:
       - name: Checkout
         uses: actions/checkout@v7
       - name: Setup Typst
         uses: typst-community/setup-typst@v5.1.0
       - name: Make PDFs
         run: python make.py
